version: '3'

services:
  postgresql:
    image: postgres
    container_name: root
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=root3
      - POSTGRES_PASSWORD=root2
      - POSTGRES_DATABASE=root1
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-lesson
    ports:
      - '6379-6379'